### ISSUE TITLE
Add override example

### ISSUE THREAD

**Issue by loevgaard** [loevgaard/SyliusBrandPlugin#48]
Add an example where for example the model is overriden:

```
loevgaard_sylius_brand:
    resources:
        brand:
            classes:
                model: App\Entity\Brand
```
